### ISSUE TITLE
Linux x86_64 release artifacts

### ISSUE THREAD

**Issue by davewongillies** [erichelgeson/minivmac#3]
Currently your release artifacts of minivmac for Linux appear to only be for ARM64

```
file ~/bin/minivmac-lx64-Plus
/home/daveg/bin/minivmac-lx64-Plus: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=e4ddefa0e0a1e9ee315aca4430897defbb1d55a1, for GNU/Linux 3.7.0, stripped
```

Any chance you can build them for x86_64 as well? Thanks!

**Comment by erichelgeson** [comment]
Ahh odd - I'm building on my M3 Macbook Pro so it seems the underlying linux container defaulted to aarch64, which makes sense I suppose. Added `--platform linux/amd64` to the docker build command seems to fix it:

```bash
$ file minivmac-lx64-Plus
minivmac-lx64-Plus: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a0ab4312e98416f84d06883e15b8c8a21925986b, for GNU/Linux 3.2.0, stripped
```

I dont think there's much demand for aarch64 linux, and there seems to be an underlying issue with the build system not cross compiling correctly, but that's a job for later.
