### ISSUE TITLE
System 7.1 crashes with system error 4 with latest build

### ISSUE THREAD

**Issue by Renegade661** [erichelgeson/minivmac#5]
Hi,
System 7.1 (french) crashes on system error 4 with latest build (2024.03.09), while the same system is perfectly stable with build 2023.09.24. I'm willing to test anything you might ask.
Zipped HDA image file is uploaded here: https://easyupload.io/gy8cs7
![Capture d’écran 2024-04-18 à 10 40 58](https://github.com/erichelgeson/minivmac/assets/68006114/a5ec598a-0552-46a9-bf76-8ecbdaa4d5ac)

**Comment by Naibel** [comment]
Hi @Renegade661 ! I managaged to make your image work just fine on the latest build (2024.03.09) by following what was written on the changelog :

`"If you get a Divide by Zero error on startup switch the emulation speed to 1x (Control-S-Z) - After you are past the error you can switch back to faster emulation speeds. Fast emulator speeds and AppleTalk don't seem to mix!"`

And _tada_ !
![Capture d’écran 2024-05-12 à 20 47 16](https://github.com/erichelgeson/minivmac/assets/14925454/06b5d255-d78c-4191-a0c7-4d085d9af257)

"Erreur numéro 4" is basically a "Divide by Zero" error, maybe that's what wasn't clear on the System 7.1's French version.
Don't forget to switch back to normal speed once the Finder is displayed or else your experience will be veerrrrryyyy slooooowwww...

**Comment by Renegade661** [comment]
> Hi @Renegade661 ! I managaged to make your image work just fine on the latest build (2024.03.09) by following what was written on the changelog :
> 
> `"If you get a Divide by Zero error on startup switch the emulation speed to 1x (Control-S-Z) - After you are past the error you can switch back to faster emulation speeds. Fast emulator speeds and AppleTalk don't seem to mix!"`
> 
> And _tada_ ! !
> "Erreur numéro 4" is basically a "Divide by Zero" error, maybe that's what wasn't clear on the System 7.1's French version. Don't forget to switch back to normal speed once the Finder is displayed or else your experience will be veerrrrryyyy slooooowwww...

Hi @Naibel ,
Geez, you're right! I had no idea System Error 4 was the "divide by zero" error. Being a bit impatient, I always started miniVMac with emulation speed to "all out".
Thanks for finding this out !

**Comment by erichelgeson** [comment]
I'll remove the AppleTalk from the default build (maybe provide a 2nd build with appletalk and speed at 1x default?) right now it's too easy to have an issue like this. Thanks for reporting and I'll close this once resolved.

**Comment by erichelgeson** [comment]
Resolved in latest build
